name: 'Copy to Dropbox'
description: 'Uploads artifacts to dropbox'
inputs:
  token: 
    description: 'DropBox access token'
    required: true
    default: 'error'
  srcPath:
    description: 'Path of assets to upload'
    required: true
  dstPath:
    description: 'Path on Dropbox to place assets'
    required: true
  timestamp:
    description: 'Flag to append dstPath with a timestamp'
    required: false
    default: 'false'
  projectName:
    description: 'Name of the project'
    required: true
runs:
  using: 'node12'
  main: 'main.js'