name: 'Copy to Dropbox'
description: 'Uploads artifacts to dropbox'
inputs:
  token: 
    description: 'DropBox access token'
    required: true
    default: 'error'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'main.js'